name: 'Build deploy'
on:
  push:
jobs:
  docs-build:
    uses: kube-green/website/.github/workflows/docs-build.yml@main
  github-pages:
    needs: docs-build
    uses: kube-green/website/.github/workflows/github-pages.yml@main

