name: 'Build deploy'
on:
  push:
jobs:
  docs-build:
    uses: kube-green/website/.github/workflows/docs-build.yml@initial-impl
  github-pages:
    needs: docs-build
    uses: kube-green/website/.github/workflows/github-pages.yml@initial-impl
    if: ${{ github.ref == 'refs/heads/main' }}
