name: GitHub Pages
on: workflow_call
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version: [1.17]
        node_version: ["lts/*"]
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
      - name: Get cache build
        uses: actions/cache@v2
        with:
          path: build
          key: build-website-${{ github.sha }}-${{ github.run_id }}
      - uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
